version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      hashicorp:
        patterns:
          - "github.com/hashicorp/*"
      all-other:
        patterns:
          - "*"
        exclude-patterns:
          - "github.com/hashicorp/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
